from __future__ import annotations

# pyright: reportMissingImports=false, reportMissingTypeArgument=false, reportUnknownParameterType=false
# pyright: reportImplicitOverride=false, reportUnknownArgumentType=false, reportUnknownMemberType=false
# pyright: reportUnknownVariableType=false, reportAny=false, reportExplicitAny=false
# pyright: reportImplicitStringConcatenation=false, reportUnusedCallResult=false
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import httpx
import vcr

BUSINESS_API_BASE = "https://business-api.tiktok.com"
ADVERTISER_INFO_PATH = "/open_api/v1.3/advertiser/info/"
DEFAULT_CASSETTE_PATH = "spikes/cassettes/s3_business_error.yaml"

FILTER_HEADERS = [
    # TikTok Business API uses Access-Token, not Authorization: Bearer.
    ("Access-Token", "REDACTED"),
    ("Authorization", "REDACTED"),
    ("X-Tt-Access-Token", "REDACTED"),
]

RESPONSE_TOKEN_PATTERNS = (
    re.compile(r"Bearer [A-Za-z0-9_-]{20,}"),
    re.compile(r"[A-Za-z0-9_-]{40,}"),
)

CASSETTE_LEAK_PATTERNS = (
    ("bearer-token", re.compile(r"Bearer [A-Za-z0-9_-]{20,}")),
    (
        "access-token-json",
        re.compile(r"access_token[\"']?\s*:\s*[\"'][A-Za-z0-9_-]{20,}"),
    ),
)


class BusinessApiError(Exception):
    """Spike prototype contract for Wave 1 T7 production BusinessApiError.

    Wave 1 T7 should preserve these field names and constructor semantics:
    code, message, request_id, and context. The cassette and tests generated by
    this spike are intended to be lifted into the production decoder suite.
    """

    def __init__(
        self,
        code: int,
        message: str,
        request_id: str | None = None,
        context: dict | None = None,
    ) -> None:
        self.code: int = code
        self.message: str = message
        self.request_id: str | None = request_id
        self.context: dict | None = context
        super().__init__(str(self))

    def __str__(self) -> str:
        return (
            f"BusinessApiError(code={self.code}, "
            f"message={self.message!r}, request_id={self.request_id})"
        )


def decode_business_response(body: dict) -> dict:
    """Decode HTTP 200 + code != 0 envelope per TikTok Business API; mirror in Wave 1 T7."""
    if body["code"] != 0:
        raise BusinessApiError(
            code=body["code"],
            message=body.get("message", ""),
            request_id=body.get("request_id"),
        )
    return body.get("data", body)


def scrub_response_body(response: dict) -> dict:
    return _scrub_value(response)


def record_invalid_call(
    token: str,
    advertiser_id: str = "doesnotexist",
    *,
    cassette_path: str = DEFAULT_CASSETTE_PATH,
) -> dict:
    Path(cassette_path).parent.mkdir(parents=True, exist_ok=True)

    with configured_vcr().use_cassette(cassette_path, record_mode="once"):
        response = _request_invalid_advertiser_info(token, advertiser_id)

    if response.status_code != 200:
        raise RuntimeError(
            "Expected TikTok Business API to return HTTP 200 with non-zero code "
            f"for the invalid advertiser/info spike call, got HTTP {response.status_code}. "
            "Record this as a separate S3 finding in spikes/s3_results.md."
        )

    body = response.json()
    if body.get("code") == 0:
        raise RuntimeError(
            "Expected a non-zero TikTok Business API code for the deliberately "
            f"invalid advertiser_id={advertiser_id!r}, got code=0."
        )
    return body


def verify_cassette_no_leaks(cassette_path: str) -> bool:
    return not _find_cassette_leaks(cassette_path)


def configured_vcr() -> vcr.VCR:
    return vcr.VCR(
        filter_headers=FILTER_HEADERS,
        before_record_response=scrub_response_body,
        decode_compressed_response=True,
    )


def main() -> int:
    blocked_prod_names = _prod_token_env_names()
    if blocked_prod_names:
        print(
            "Refusing to run with production-looking TikTok token env vars set: "
            f"{', '.join(blocked_prod_names)}. Use only TIKTOK_BUSINESS_SANDBOX_TOKEN.",
            file=sys.stderr,
        )
        return 2

    token = os.getenv("TIKTOK_BUSINESS_SANDBOX_TOKEN")
    if not token:
        print(
            "TIKTOK_BUSINESS_SANDBOX_TOKEN is unset; export a sandbox token before recording S3.",
            file=sys.stderr,
        )
        return 2

    body = record_invalid_call(token)
    try:
        decode_business_response(body)
    except BusinessApiError as error:
        print(f"Recorded expected BusinessApiError envelope: {error}")
    else:
        raise RuntimeError("Expected decode_business_response to raise BusinessApiError.")

    leaks = _find_cassette_leaks(DEFAULT_CASSETTE_PATH)
    if leaks:
        leak_lines = "\n".join(
            f"line {line_number}: {pattern_name}: {line}"
            for pattern_name, line_number, line in leaks
        )
        raise RuntimeError(
            "Cassette leak check failed. Do NOT git-add the cassette until this is fixed.\n"
            f"{leak_lines}"
        )

    print(f"Cassette scrub verification passed: {DEFAULT_CASSETTE_PATH}")
    return 0


def _request_invalid_advertiser_info(token: str, advertiser_id: str) -> httpx.Response:
    return httpx.get(
        f"{BUSINESS_API_BASE}{ADVERTISER_INFO_PATH}",
        headers={"Access-Token": token},
        params={"advertiser_ids": json.dumps([advertiser_id], separators=(",", ":"))},
        timeout=30.0,
    )


def _scrub_string(value: str) -> str:
    scrubbed = value
    for pattern in RESPONSE_TOKEN_PATTERNS:
        scrubbed = pattern.sub("<REDACTED>", scrubbed)
    return scrubbed


def _scrub_value(value: Any) -> Any:
    if isinstance(value, str):
        return _scrub_string(value)
    if isinstance(value, bytes):
        try:
            return _scrub_string(value.decode("utf-8")).encode("utf-8")
        except UnicodeDecodeError:
            return value
    if isinstance(value, list):
        return [_scrub_value(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_scrub_value(item) for item in value)
    if isinstance(value, dict):
        return {key: _scrub_value(item) for key, item in value.items()}
    return value


def _find_cassette_leaks(cassette_path: str) -> list[tuple[str, int, str]]:
    path = Path(cassette_path)
    if not path.exists():
        return [("missing-cassette", 0, str(path))]

    leaks: list[tuple[str, int, str]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        for pattern_name, pattern in CASSETTE_LEAK_PATTERNS:
            if pattern.search(line):
                leaks.append((pattern_name, line_number, line.strip()))
    return leaks


def _prod_token_env_names() -> list[str]:
    return sorted(
        name
        for name in os.environ
        if "PROD" in name.upper()
        and "TOKEN" in name.upper()
        and name.upper().startswith("TIKTOK_BUSINESS")
    )


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
